### PR TITLE
Feature/customize app

### PR DESCRIPTION
**Pull request by rngShard**

### CODE REVIEW

**Comment by rngShard** [comment]
Hi @EmilStenstrom, opened PR against wrong repo, meant to merge into my for instead. Sorry ...

**Comment by EmilStenstrom** [comment]
@rngShard I'm happy that you found mybgg useful! Looks like your making something that others will use (which is great!)? Or is just for you?

**Comment by rngShard** [comment]
Happy to have found your repo as well, got me on the ground running incredibly quickly :) only small customization to the update script, am not planning any front-end overhaul quite yet.

Do you think the parameter reading with secret API-Admin-Key could be useful? Can to a PR to your repo if you think this may be helpful. Would need to add explanations to the readme first though.

**Comment by EmilStenstrom** [comment]
@rngShard I'm a bit worried about putting secrets in files. For instance, and can see people putting their secret in the secret.json.example file, and commiting it to their repo, which would be a security issue. Maybe we could make the script look for a secret.json file if no key is given at the prompt, for power users like you? I've seen lots of people new to git setting up this script, and I really want to keep them safe.

**Comment by rngShard** [comment]
File is only considered when no key is provided as command line parameter, it's only a couple of lines adjustment though. Shall I make a proper PR out of it?

**Comment by EmilStenstrom** [comment]
Please do! Just leave out the example secrets file, to keep beginners from fiddling with things they shiuldn't touch :)

**Pull request closed without merging**
