### PR TITLE
Include supported player counts and min-age filter

### PR DESCRIPTION
**Pull request by boglesby03**
Add supported players in italic to the recommended players.  There's probably a better way to manage the games with high player counts.

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
Hi,

When running this locally, I get this error:

```
[...]
DEBUG:mybgg.bgg_client:Successfully parsed: Xia: Embers of a Forsaken Star (id: 199329).
DEBUG:mybgg.bgg_client:Successfully parsed: Xia: Legends of a Drift System (id: 82222).
DEBUG:mybgg.bgg_client:Successfully parsed: Xia: Missions and Powers (id: 244564).
DEBUG:mybgg.bgg_client:Successfully parsed: Yamataï (id: 213893).
DEBUG:mybgg.bgg_client:Successfully parsed: Yokohama (id: 196340).
Traceback (most recent call last):
  File "/home/emilstenstrom/Projects/mybgg/scripts/download_and_index.py", line 77, in <module>
    main(args)
  File "/home/emilstenstrom/Projects/mybgg/scripts/download_and_index.py", line 15, in main
    collection = downloader.collection(
  File "/home/emilstenstrom/Projects/mybgg/scripts/mybgg/downloader.py", line 61, in collection
    games = [
  File "/home/emilstenstrom/Projects/mybgg/scripts/mybgg/downloader.py", line 62, in <listcomp>
    BoardGame(
  File "/home/emilstenstrom/Projects/mybgg/scripts/mybgg/models.py", line 19, in __init__
    self.minage = game_data["min_age"]
KeyError: 'min_age'
```

So it seems this code has a problem when a game does not have a min-age set, such as with Yokohama in my own collection. Would you mind taking a look at this? Or maybe separate that change from this PR, because it's not related. You decide, I like both of them!

**Comment by EmilStenstrom** [comment]
Fixes #51 and #47

**Comment by boglesby03** [comment]
I'll look into it.  Sorry about them coming in together.  Didn't mean that
to happen.

**Comment by EmilStenstrom** [comment]
No need to be sorry, I'm happy for all the help I can get! :)

**Pull request closed without merging**
