### PR TITLE
feature: Adding Github Actions

### PR DESCRIPTION
**Pull request by MatyiFKBT**
I've created a Github Actions workflow that runs every Monday at 00:00 to run the downloader script.
For this to work, you need to set a secret with your Algolia admin key as `APIKEY` in your fork of the repository.
I've also included a check for this secret, if it's not set, the script won't run. ([example run](https://github.com/MatyiFKBT/mybgg/runs/1676800591))
Let me know what you think!

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
This is a great addition. I'm currently using CircleCI myself, but pointing towards GitHub Actions is much better. I need some time look at this, but I'll merge this eventually! :) Thanks!

**Comment by EmilStenstrom** [comment]
@MatyiFKBT Now I've had the chance to look at this. It's awesome! I'll change the interval to once an hour, so new games appear more quickly. Thanks for contributing!

**Comment by MatyiFKBT** [comment]
No problem! Glad you like it.
Also I'd consider changing it to daily instead, since the free tier on Algolia only allows a limited amount of operations.

**Comment by EmilStenstrom** [comment]
@MatyiFKBT I've been running it on CircleCI for years with hourly setting, so I think it should be fine! 😃 Maybe I should consider some kind of checksum that avoids reindexing info that's already there, I don't know...

**Pull request merged**
